name       : libraw
version    : 0.18.6
release    : 6
source     :
    - https://www.libraw.org/data/LibRaw-0.18.6.tar.gz : e5b8acca558aa457bc9214802004320c5610d1434c2adb1f3ea367f026afa53b
license    :
    - LGPL-2.1
    - CDDL-1.0
component  : multimedia.library
summary    : LibRaw is a library for reading RAW files obtained from digital photo cameras (CRW/CR2, NEF, RAF, DNG, and others).
description: |
    LibRaw is a library for reading RAW files obtained from digital photo cameras (CRW/CR2, NEF, RAF, DNG, and others).
builddeps  :
    - pkgconfig(jasper)
    - pkgconfig(lcms2)
    - libjpeg-turbo-devel
patterns   :
    - utils : /usr/bin
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
