name       : libraw
version    : 0.18.7
release    : 7
source     :
    - https://www.libraw.org/data/LibRaw-0.18.7.tar.gz : 87e347c261a8e87935d9a23afd750d27676b99f540e8552314d40db0ea315771
license    :
    - LGPL-2.1
    - CDDL-1.0
component  : multimedia.library
summary    : LibRaw is a library for reading RAW files obtained from digital photo cameras (CRW/CR2, NEF, RAF, DNG, and others).
description: |
    LibRaw is a library for reading RAW files obtained from digital photo cameras (CRW/CR2, NEF, RAF, DNG, and others).
builddeps  :
    - pkgconfig(jasper)
    - pkgconfig(lcms2)
    - libjpeg-turbo-devel
patterns   :
    - utils : /usr/bin
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
