name       : libraw
version    : 0.20.2
release    : 14
source     :
    - https://github.com/LibRaw/LibRaw/archive/refs/tags/0.20.2.tar.gz : 02df7d403b34602b769bb38e5bf7d4258e075eeefbe980b6832e6e1491989d60
homepage   : https://www.libraw.org/
license    :
    - CDDL-1.0
    - LGPL-2.1-or-later
component  :
    - multimedia.library
    - utils : multimedia.graphics
summary    :
    - LibRaw is a library for reading RAW files from digital cameras
    - utils : Tools for Libraw
description:
    - LibRaw is a library for reading RAW files obtained from digital photo cameras (CRW/CR2, NEF, RAF, DNG, and others).
    - utils : Tools for Libraw
avx2       : yes
optimize   :
    - speed
builddeps  :
    - pkgconfig(jasper)
    - pkgconfig(lcms2)
    - pkgconfig(libturbojpeg)
patterns   :
    - utils : /usr/bin
setup      : |
    %reconfigure --disable-static
build      : |
    %make
install    : |
    %make_install
    rm -rf $installdir/usr/share/doc
