name       : libraw
version    : 0.18.13
release    : 10
source     :
    - https://github.com/LibRaw/LibRaw/archive/0.18.13.tar.gz : 7a2ebb256b1b8398e697a60290ac7b4ea37fe38272231cccce6d380fff4483c1
license    :
    - LGPL-2.1-or-later
    - CDDL-1.0
component  : multimedia.library
summary    : LibRaw is a library for reading RAW files from digital cameras
description: |
    LibRaw is a library for reading RAW files obtained from digital photo cameras (CRW/CR2, NEF, RAF, DNG, and others).
builddeps  :
    - pkgconfig(jasper)
    - pkgconfig(lcms2)
    - pkgconfig(libturbojpeg)
patterns   :
    - utils : /usr/bin
setup      : |
    %reconfigure --disable-static
build      : |
    %make
install    : |
    %make_install
