name       : libraw
version    : 0.19.5
release    : 11
source     :
    - https://github.com/LibRaw/LibRaw/archive/0.19.5.tar.gz : 9a2a40418e4fb0ab908f6d384ff6f9075f4431f8e3d79a0e44e5a6ea9e75abdc
license    :
    - LGPL-2.1-or-later
    - CDDL-1.0
component  : multimedia.library
summary    : LibRaw is a library for reading RAW files from digital cameras
description: |
    LibRaw is a library for reading RAW files obtained from digital photo cameras (CRW/CR2, NEF, RAF, DNG, and others).
builddeps  :
    - pkgconfig(jasper)
    - pkgconfig(lcms2)
    - pkgconfig(libturbojpeg)
patterns   :
    - utils : /usr/bin
setup      : |
    %reconfigure --disable-static
build      : |
    %make
install    : |
    %make_install
