name       : libraw
version    : 0.17.0
release    : 1
source     :
    - http://www.libraw.org/data/LibRaw-0.17.0.tar.gz : e643c20945d548aac1eaa1f5573bf74050e0f49ec6a53a6843dc2a2cfb647310
license    :
    - LGPL-2.1
    - CDDL-1.1
summary    : LibRaw is a library for reading RAW files obtained from digital photo cameras (CRW/CR2, NEF, RAF, DNG, and others).
description: |
    LibRaw is a library for reading RAW files obtained from digital photo cameras (CRW/CR2, NEF, RAF, DNG, and others).
builddeps  :
    - pkgconfig(lcms2)
patterns   :
    - utils: /usr/bin
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
