name       : libraw
version    : 0.18.10
release    : 8
source     :
    - https://www.libraw.org/data/LibRaw-0.18.10.tar.gz : 08c9bbf2bb5f8aece783d05e0b5268aaae5562a34d940e17ee7a22cbc2fb994e
license    :
    - LGPL-2.1-only
    - CDDL-1.0
component  : multimedia.library
summary    : LibRaw is a library for reading RAW files obtained from digital photo cameras (CRW/CR2, NEF, RAF, DNG, and others).
description: |
    LibRaw is a library for reading RAW files obtained from digital photo cameras (CRW/CR2, NEF, RAF, DNG, and others).
builddeps  :
    - pkgconfig(jasper)
    - pkgconfig(lcms2)
    - libjpeg-turbo-devel
patterns   :
    - utils : /usr/bin
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
